### ISSUE TITLE
Rubric Score

### ISSUE THREAD

**Issue by Kavit900** [alexandertrevor/capstone#1]
**Criteria 1: Maze Solving**

- _Score Level:_ 4

**Criteria 2: Sorting Algorithms**

- _Score Level:_ 4

**Criteria 3: Overall Code Quality and Functionality**

- _Score Level:_ 4

**Criteria 4: Algorithm Tailoring**

- _Score Level:_ 4

Overall Score: 16/16

Your work definitely meets the project requirements -- awesome work!! You demonstrate an excellent understanding of Python. I am really confident that you will be able to apply these skills to your future endeavors. :)

Good luck!

**Comment by alexandertrevor** [comment]
Thank you.

**Comment by Kavit900** [comment]
you welcome, closing this issue.
